index:
    path: /{_locale}
    controller: App\Controller\DefaultController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'en'

contact:
    path: /{_locale}/contact
    controller: App\Controller\DefaultController::contact
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

boutique:
    path: /{_locale}/boutique
    controller: App\Controller\BoutiqueController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

produits:
    path: /{_locale}/produits/{idCategory}
    controller: App\Controller\BoutiqueController::produits
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

testDeBourin:
    path: /{_locale}/test
    controller:  App\Controller\DefaultController::testDeBourin
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

searchProduits:
    path: /{_locale}/produits/{search}
    controller: App\Controller\BoutiqueController::searchProduits
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

panier:
    path: /{_locale}/panier
    controller: App\Controller\PanierController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

ajouterArticle:
    path: /{_locale}/panier/ajouter/{idProduit}
    controller: App\Controller\PanierController::panierAjouter
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

enleverArticle:
    path: /{_locale}/panier/enlever/{idProduit}
    controller: App\Controller\PanierController::panierEnlever
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

supprimerLigne:
    path: /{_locale}/panier/supprimerLigne/{idProduit}
    controller: App\Controller\PanierController::panierSupprimerLigne
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'


supprimer:
   path: /{_locale}/panier/suppressionPanier
   controller: App\Controller\PanierController::supprimerPanier
   requirements:
       _locale: '%app.supported_locales%'
   defaults:
       _locale: 'fr'


usager_accueil:
    path: /{_locale}/usager
    controller: App\Controller\UsagerController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

usager_inscription:
    path: /{_locale}/usager/new
    controller: App\Controller\UsagerController::new
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

panier_validation:
    path: /{_locale}/panier/commande_validation
    controller: App\Controller\PanierController::validation
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

login:
    path: /{_locale}/login
    controller : App\Controller\SecurityController::login
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

app_logout:
    path: /{_locale}/logout
    methods: GET
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'
