index:
    path: /
    controller: App\Controller\DefaultController::index

contact:
    path: /contact
    controller: App\Controller\DefaultController::contact

boutique:
    path: /boutique
    controller: App\Controller\BoutiqueController::index

produits:
    path: /produits/{idCategory}
    controller: App\Controller\BoutiqueController::produits

testDeBourin:
    path: /test
    controller:  App\Controller\DefaultController::testDeBourin

searchProduits:
    path: /produits/{search}
    controller: App\Controller\BoutiqueController::searchProduits

panier:
    path: /panier
    controller: App\Controller\PanierController::index

ajouterArticle:
    path: /panier/ajouter/{idProduit}/{quantite}
    controller: App\Controller\PanierController::panierAjouter
